package ru.sibsutis.cryptomethods.algorithms;

import ru.sibsutis.cryptomethods.core.Gambler;
import ru.sibsutis.cryptomethods.core.Generator;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class CryptoPokerUI extends JFrame {

    private BigInteger p;
    private int n;
    private final int cards = 52;
    private List<BigInteger> deck = new ArrayList<>();
    private final List<Gambler> players = new ArrayList<>();

    private final JSpinner spinnerPlayers = new JSpinner(new SpinnerNumberModel(2, 2, 10, 1));
    private final JButton btnGenerateKeys = new JButton("Generate keys");
    private final JButton btnShuffleDeal = new JButton("Shuffle & Deal");
    private final JButton btnAutoP = new JButton("Auto-generate p");
    private final JTextArea out = new JTextArea(20, 60);
    private final JCheckBox chkShowEncrypted = new JCheckBox("Show encrypted values (for debug)", false);
    private final JTextField txtP = new JTextField(20);

    public CryptoPokerUI() {
        super("Crypto Poker — Texas Hold'em (mental poker)");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        buildUI();
        pack();
        setLocationRelativeTo(null);
    }

    private void buildUI() {
        JPanel top = new JPanel(new FlowLayout(FlowLayout.LEFT));
        top.add(new JLabel("Players:"));
        top.add(spinnerPlayers);

        top.add(new JLabel("p:"));
        top.add(txtP);

        top.add(btnGenerateKeys);
        btnAutoP.setText("Generate p");
        top.add(btnAutoP);
        top.add(btnShuffleDeal);
        top.add(chkShowEncrypted);

        out.setEditable(false);
        out.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
        JScrollPane scroll = new JScrollPane(out);

        add(top, BorderLayout.NORTH);
        add(scroll, BorderLayout.CENTER);

        btnGenerateKeys.addActionListener(this::onGenerateKeys);
        btnShuffleDeal.addActionListener(this::onShuffleDeal);

        btnAutoP.addActionListener(e -> {
            p = Generator.generatePrimeNumber(50);
            txtP.setText(p.toString());
            append("Auto-generated p = " + p + "\n");
        });
    }

    private void append(String s) {
        out.append(s);
        out.setCaretPosition(out.getDocument().getLength());
    }

    private void onGenerateKeys(ActionEvent e) {
        n = (Integer) spinnerPlayers.getValue();
        deck.clear();
        players.clear();

        for (int i = 2; i < cards + 2; i++)
            deck.add(BigInteger.valueOf(i));

        String pText = txtP.getText().trim();

        if (!pText.isEmpty()) {
            try {
                p = new BigInteger(pText);
                if (!p.isProbablePrime(30)) {
                    append("WARNING: p is not prime! (probable)\n");
                }
            } catch (Exception ex) {
                append("Invalid p entered — auto-generating prime.\n");
                p = Generator.generatePrimeNumber(50);
                txtP.setText(p.toString());
            }
        } else {
            p = Generator.generatePrimeNumber(50);
            txtP.setText(p.toString());
            append("p wasn't set — autogenerated p = " + p + "\n");
        }

        for (int i = 0; i < n; i++) {
            players.add(new Gambler(p));
        }

        append(String.format("Keys generated for %d players. Deck initialized (%d cards).\n", n, deck.size()));
        append("Ready. Click 'Shuffle & Deal' to run protocol.\n\n");
    }

    private void onShuffleDeal(ActionEvent e) {
        if (players.isEmpty()) {
            append("Please press 'Generate keys' first.\n");
            return;
        }

        List<BigInteger> workDeck = new ArrayList<>(deck);

        append("== Phase 1: every player encrypts the deck and shuffles ==\n");
        for (int i = 0; i < n; i++) {
            Gambler g = players.get(i);
            workDeck = g.encHand(workDeck, p);
            Collections.shuffle(workDeck);
            append(String.format(" Player %d encrypted & shuffled.\n", i + 1));
        }
        if (chkShowEncrypted.isSelected()) {
            append("Encrypted deck (top -> bottom):\n");
            for (int i = 0; i < Math.min(10, workDeck.size()); i++)
                append("  " + i + ": " + workDeck.get(i) + "\n");
            append("\n");
        }

        append("== Phase 2: dealing encrypted private cards (2 per player) ==\n");
        for (int i = 0; i < n; i++) {
            List<BigInteger> encryptedHand = new ArrayList<>();
            for (int c = 0; c < 2; c++) {
                encryptedHand.add(workDeck.removeLast());
            }
            players.get(i).takeHand(encryptedHand);
            append(String.format(" Player %d received 2 encrypted cards.\n", i + 1));
        }

        append("\n== Phase 3: decrypting each player's private cards (only owner learns cards) ==\n");
        for (int i = 0; i < n; i++) {
            List<BigInteger> hand = players.get(i).passHand();

            for (int j = 1; j < n + 1; j++) {
                hand = players.get((i + j) % n).deEncHand(hand, p);
            }
            players.get(i).takeHand(hand);
            append(String.format(" Player %d private cards revealed to owner: %s\n", i + 1, humanHand(hand)));
        }

        append("\n== Phase 4: preparing community (board) 5 cards ==\n");
        List<BigInteger> boardEncrypted = new ArrayList<>();
        for (int c = 0; c < 5; c++) {
            boardEncrypted.add(workDeck.removeLast());
        }
        append("  5 encrypted community cards taken.\n");

        append("  All players will sequentially de-encrypt the board to reveal community cards.\n");
        for (int i = 0; i < n; i++) {
            boardEncrypted = players.get(i).deEncHand(boardEncrypted, p);
            append(String.format("   Player %d applied decryption step.\n", i + 1));
        }

        append("\n== Final: revealed hands and board ==\n");
        for (int i = 0; i < n; i++) {
            List<BigInteger> hand = players.get(i).passHand();
            append(String.format(" Player %d: %s\n", i + 1, humanHand(hand)));
        }

        append("\n Board (5 cards): " + humanHand(boardEncrypted) + "\n");
        append("\nProtocol finished.\n\n");
    }

    private String cardName(BigInteger v) {
        int id = v.intValue() - 2;
        if (id < 0 || id >= 52) return v.toString();
        String[] ranks = {"2","3","4","5","6","7","8","9","10","J","Q","K","A"};
        String[] suits = {"♣","♦","♥","♠"};
        int rank = id % 13;
        int suit = id / 13;
        return ranks[rank] + suits[suit];
    }

    private String humanHand(List<BigInteger> hand) {
        if (hand == null) return "[]";
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < hand.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(cardName(hand.get(i)));
        }
        sb.append("]");
        return sb.toString();
    }

    public static void runPoker() {
        SwingUtilities.invokeLater(() -> {
            CryptoPokerUI ui = new CryptoPokerUI();
            ui.setVisible(true);
        });
    }
}
